name: Assess Test Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
    - name: Evaluate Coverage
      run: |
        cd tests
        ./run_tests.sh
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: tests/.coverage
        token: ${{ secrets.CODECOV_TOKEN }}

